### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by schell** [schell/aeson-tiled#7]
Hiya, I no longer have free time to dedicate to this library. Would anyone like to take over maintainership? 

I'll tag a few of you that have contributed in the past. Thank you! 

* @isovector 
* @hussein-aitlahcen 
* @toku-sa-n 
* @dpwiz

**Comment by dpwiz** [comment]
I will.

**Comment by dpwiz** [comment]
Also https://github.com/haskell-game looks like a good place for it.

**Comment by schell** [comment]
Thank you @dpwiz ! I will make you an admin on this repo and you may do what you like (including moving it to the haskell-game org).

**Comment by dpwiz** [comment]
@schell Please add me on [hackage](https://hackage.haskell.org/user/AlexanderBondarenko) too so I can upload new packages.
