### ISSUE TITLE
Embedded tileset tiles don't parse 

### ISSUE THREAD

**Issue by isovector** [schell/aeson-tiled#9]
The `tilesetTiles` field appears to always be empty. Here's some sample JSON:

```json
...
 "tilesets":[
        {
         "columns":8,
         "firstgid":1,
         "image":"..\/tilesets\/basic.png",
         "imageheight":240,
         "imagewidth":128,
         "margin":0,
         "name":"basic",
         "spacing":0,
         "tilecount":120,
         "tileheight":16,
         "tiles":[
                {
                 "id":0,
                 "properties":[
                        {
                         "name":"walkable",
                         "type":"bool",
                         "value":false
                        }]
                }, 
...

```

Notice that `tiles` is a _list_ of `{"id": ..., ...}` objects, not a map itself.

**Comment by dpwiz** [comment]
This repository is kinda archived, please file this at its [new home](https://github.com/haskell-game/aeson-tiled).

(for some reason the issue section was disabled there, which is now fixed)

**Comment by isovector** [comment]
Done. Probably worth archiving this repo properly to avoid future confusion though!

**Comment by schell** [comment]
I will put this in archive/read-only mode and link to the new repo in the readme. Thanks all!
